from fpdf import FPDF
import os

def generate_pdf(session) -> str:
    pdf = FPDF()
    pdf.add_page()

    # Header
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(63, 84, 186)
    pdf.cell(0, 12, "PsySense AI - Candidate Assessment Report", ln=True, align="C")
    pdf.ln(4)

    # Divider
    pdf.set_draw_color(63, 84, 186)
    pdf.set_line_width(0.8)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    # Candidate info
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(40, 40, 40)
    pdf.cell(0, 8, f"Candidate Name:    {session.candidate_name}", ln=True)
    pdf.cell(0, 8, f"Interview Date:    {session.created_at.strftime('%d %B %Y, %H:%M')} UTC", ln=True)
    pdf.cell(0, 8, f"Questions Answered: {session.questions_answered}", ln=True)
    pdf.ln(4)

    # Final score box
    pdf.set_fill_color(63, 84, 186)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 12, f"  Final Behavioral Score:  {session.final_score} / 100", ln=True, fill=True)
    pdf.ln(6)

    # Signal breakdown
    pdf.set_text_color(40, 40, 40)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, "Signal Breakdown", ln=True)

    signals = [
        ("Answer Quality (Cognitive)", session.cognitive_score),
        ("Emotional Tone (Speech)", session.emotion_score),
        ("Attentiveness (Engagement)", session.engagement_score),
    ]

    pdf.set_font("Helvetica", "", 11)
    for label, score in signals:
        bar_width = int((score / 10) * 80)  # scores are 0-10, bar max 80mm
        pdf.cell(80, 8, f"  {label}:", border=0)
        pdf.set_fill_color(63, 84, 186)
        pdf.cell(bar_width, 6, "", fill=True)
        pdf.cell(0, 6, f"  {score:.1f} / 10", ln=True)
        pdf.ln(2)

    pdf.ln(4)

    # Flag status
    pdf.set_font("Helvetica", "B", 11)
    if session.flagged:
        pdf.set_text_color(231, 76, 60)
        pdf.cell(0, 8, "FLAGGED - Score below threshold (50). Recommend manual review.", ln=True)
    else:
        pdf.set_text_color(46, 204, 113)
        pdf.cell(0, 8, "PASSED - Score meets minimum threshold.", ln=True)

    pdf.ln(6)

    # Footer
    pdf.set_text_color(150, 150, 150)
    pdf.set_font("Helvetica", "I", 9)
    pdf.cell(0, 8, "Generated by PsySense AI Behavioral Interview System", ln=True, align="C")

    # Save
    os.makedirs("data", exist_ok=True)
    path = f"data/report_{session.id}_{session.candidate_name.replace(' ', '_')}.pdf"
    pdf.output(path)
    return path